import { library } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
import Vue from 'vue'


import {faEnvelope, faClock} from '@fortawesome/free-regular-svg-icons'
import {faPhone, faPlus, faMinus, faRoad, faVideo, faDroplet, faGear, faBuilding, faChartColumn, faAngleRight, faLink} from '@fortawesome/free-solid-svg-icons'
import { faFacebookF, faTwitter, faYoutube, faInstagram, faGoogle, faLinkedinIn} from '@fortawesome/free-brands-svg-icons'
import { faWifi } from '@fortawesome/free-solid-svg-icons'
import { faAngleDown } from '@fortawesome/free-solid-svg-icons'
import { faAngleLeft } from '@fortawesome/free-solid-svg-icons'
import { faFlag } from '@fortawesome/free-solid-svg-icons'
import { faMagnifyingGlass } from '@fortawesome/free-solid-svg-icons'
import { faUser } from '@fortawesome/free-solid-svg-icons'
import { faSliders } from '@fortawesome/free-solid-svg-icons'
import { faLeaf } from '@fortawesome/free-solid-svg-icons'
import { faArrowsSpin } from '@fortawesome/free-solid-svg-icons'
import { faLayerGroup } from '@fortawesome/free-solid-svg-icons'
import { faUserTie } from '@fortawesome/free-solid-svg-icons'
import { faGears } from '@fortawesome/free-solid-svg-icons'
import { faComments } from '@fortawesome/free-solid-svg-icons'
import { faBriefcase } from '@fortawesome/free-solid-svg-icons'
import { faCaretRight } from '@fortawesome/free-solid-svg-icons'
import { faAnglesRight } from '@fortawesome/free-solid-svg-icons'
import { faPlay } from '@fortawesome/free-solid-svg-icons'
import { faCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faHandHoldingHand } from '@fortawesome/free-solid-svg-icons'
import { faCircleQuestion } from '@fortawesome/free-solid-svg-icons'
import { faBuildingLock } from '@fortawesome/free-solid-svg-icons'
import { faComputer } from '@fortawesome/free-solid-svg-icons'
import { faMagnifyingGlassChart } from '@fortawesome/free-solid-svg-icons'
import { faFileCircleCheck } from '@fortawesome/free-solid-svg-icons'
import { faAward } from '@fortawesome/free-solid-svg-icons'
import { faCubes } from '@fortawesome/free-solid-svg-icons'
import { faFolderOpen } from '@fortawesome/free-solid-svg-icons'
import { faShuttleSpace } from '@fortawesome/free-solid-svg-icons'
import { faPersonDotsFromLine } from '@fortawesome/free-solid-svg-icons'
import { faLaptopCode } from '@fortawesome/free-solid-svg-icons'
import { faPhoneVolume } from '@fortawesome/free-solid-svg-icons'
import { faLocationDot } from '@fortawesome/free-solid-svg-icons'
import { faMessage } from '@fortawesome/free-regular-svg-icons'
import { faCirclePlus } from '@fortawesome/free-solid-svg-icons'
import { faCircleMinus } from '@fortawesome/free-solid-svg-icons'
import { faCloud } from '@fortawesome/free-solid-svg-icons'
import { faChartArea } from '@fortawesome/free-solid-svg-icons'
import { faCodeBranch } from '@fortawesome/free-solid-svg-icons'
import { faFolderTree } from '@fortawesome/free-solid-svg-icons'
import { faArrowLeft } from '@fortawesome/free-solid-svg-icons'
import { faArrowRight } from '@fortawesome/free-solid-svg-icons'
import { faTag } from '@fortawesome/free-solid-svg-icons'
import { faEye } from '@fortawesome/free-solid-svg-icons'
import { faQuoteLeft } from '@fortawesome/free-solid-svg-icons'
import { faUpRightAndDownLeftFromCenter } from '@fortawesome/free-solid-svg-icons'


library.add(faEnvelope, faFacebookF, faTwitter, faYoutube, faInstagram, faPhone, faClock,faPlus, faMinus, faRoad, faVideo, faDroplet, faGoogle, faGear, faBuilding, faChartColumn, faAngleRight, faLink, faLinkedinIn, faFacebookF, faTwitter, faLinkedinIn, faWifi, faYoutube, faMagnifyingGlass, faAngleDown, faAngleLeft, faFlag, faUser, faClock, faSliders, faAngleRight, faLeaf, faUser, faArrowsSpin, faLayerGroup, faUserTie, faGears, faComments, faBriefcase, faCaretRight, faAnglesRight, faPlay, faCircleCheck, faHandHoldingHand, faCircleQuestion, faBuildingLock, faComputer, faMagnifyingGlassChart, faFileCircleCheck, faAward, faCubes, faFolderOpen, faShuttleSpace, faPersonDotsFromLine, faLaptopCode, faPhoneVolume, faLocationDot, faMessage, faCirclePlus, faCircleMinus, faInstagram, faCloud, faChartArea, faCodeBranch, faFolderTree, faArrowLeft, faArrowRight, faUpRightAndDownLeftFromCenter, faTag, faEye, faQuoteLeft)

Vue.component('font-awesome-icon', FontAwesomeIcon)